image: node:4.4.5

services:
  - mongo:latest

variables:
  MONGO_URI: 'mongodb://mongo/poc-todolist'

cache:
  paths:
  - node_modules/

stages:
  - test

# test-frontend:
#   stage: test
#   script:
#     - npm install
#     - npm run test-frontend

test-backend:
  stage: test
  script:
    - npm install
    - npm install -g jasmine-core karma-jasmine karma karma-phantomjs-launcher karma-chrome-launcher mocha
    - npm run test-backend
